<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Aishwarya_29" failures="2" tests="4" name="Surefire test" time="14.069" errors="0" timestamp="2025-09-17T15:18:36 IST">
  <testcase classname="api.test.userTest" name="testPostUser" time="4.088"/>
  <testcase classname="api.test.userTest" name="testgetuserbyname" time="2.108"/>
  <testcase classname="api.test.userTest" name="testUpdateuserbyname" time="5.975">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.userTest.testUpdateuserbyname(userTest.java:75)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- testUpdateuserbyname -->
  <testcase classname="api.test.userTest" name="testdeleteuserbyusername" time="1.693">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.userTest.testdeleteuserbyusername(userTest.java:84)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- testdeleteuserbyusername -->
</testsuite> <!-- Surefire test -->
